services:
  - type: web
    name: old-man-supper-club
    env: go
    buildCommand: go build -o server ./cmd/web/main.go
    startCommand: ./server
    envVars:
      - key: DATABASE_URL
        sync: false
        placeholder: "Paste your Neon.tech connection string here"
      - key: PORT
        sync: false
        default: 3000
